name: deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: inject gpr token
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GPR_TOKEN}" > .npmrc
          echo "@deptno:registry=https://npm.pkg.github.com/" >> npmrc
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
      - run: npm ci
      - run: npm publish